name: aiya
description: A convient way to communicate with your Aiya Cloud
publish_to: "none"
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  power_file_view:
    git: https://github.com/18601673727/flutter_power_file_view.git
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.9
  permission_handler: ^10.2.0
  page_transition: ^2.0.9
  hooks_riverpod: ^2.3.5
  flutter_hooks: ^0.18.6
  fl_shared_link: ^0.0.3
  logger: ^1.3.0
  riverpod_annotation: ^2.1.0
  freezed_annotation: ^2.2.0
  flutter_riverpod: ^2.3.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  freezed: ^2.3.2
  riverpod_generator: ^2.2.0
  riverpod_lint: ^1.3.0
flutter:
  uses-material-design: true
